Update to use nginx
Failed to use .sock.
Error: command ```uwsgi uwsgi.ini```,  bind(): Input/output error [core/socket.c line 230] in uwsgi.log.
No infomation.